name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myrepo .

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/myrepo ${{ secrets.DOCKER_USERNAME }}/myrepo:22f2000148

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myrepo:22f2000148
